getwd()
x<- read.delim("C:/Users/admin/Downloads/exdata_data_household_power_consumption/household_power_consumption.txt",header = T,sep =';',stringsAsFactors = FALSE)
x1 <- subset(x,Date == '1/2/2007')
x1 <- rbind(x1,subset(x,Date=='2/2/2007'))
t2 <- paste(x1$Date,x1$Time,sep=' ')
timeset <- strptime(t2,format = "%d/%m/%Y %H:%M:%S" )
png(file= "C:/Users/admin/Documents/GitHub/ExData_Plotting1/plot4.png",height = 480,width=480)
par(mfrow=c(2,2),mar=c(4,4,2,2))
plot(timeset,as.numeric(x1$Global_active_power),ylab="Global Active Power",xlab=" ", type="l")
plot(timeset,as.numeric(x1$Voltage),ylab="Voltage",xlab="datetime",type="l")
plot(timeset,as.numeric(x1$Sub_metering_1),ylab="Energy Submetering",xlab=" ",type="l")
lines(timeset,as.numeric(x1$Sub_metering_2),col="red",type="l")
lines(timeset,as.numeric(x1$Sub_metering_3),col="blue",type="l")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lwd=1)
plot(timeset,as.numeric(x1$Global_reactive_power),ylab="Global_reactive_power",xlab="datetime",type="l")
#par("mar")
dev.off()
